import com.vanniktech.maven.publish.SonatypeHost
import org.springframework.boot.gradle.plugin.SpringBootPlugin
import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.5.4' apply false
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.vanniktech.maven.publish' version '0.30.0'
}

group = 'io.github.darkona'
version = '1.0.0'

repositories {
    mavenCentral()
    mavenLocal()
}

def filename = "${rootProject.name}-${this.version}.jar"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs += [
                "-parameters"
        ]
    }
    compileTestJava{
        options.encoding = 'UTF-8'
        options.compilerArgs += [
                "-parameters"
        ]
    }
    artifacts {
        archives jar
    }
}

jar {
    enabled = true
    archiveFileName = filename
    archiveClassifier = ''
}

mavenPublishing {

    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)

    signAllPublications()

    coordinates(group.toString(), rootProject.name, version.toString())

    pom {
        name = "Logged"
        description = "Spring-Boot Aspect-Based Logging helper that allows annotating methods so they are logged on entry, on return and on exception."
        inceptionYear = "2025"
        url = "https://github.com/Darkona/logged"
        licenses {
            license {
                name = "GNU LESSER GENERAL PUBLIC LICENSE VERSION 3"
                url = "https://www.gnu.org/licenses/lgpl-3.0.txt"
                distribution = "https://www.gnu.org/licenses/lgpl-3.0.en.html"
            }
        }
        developers {
            developer {
                id = "Darkona"
                name = "Javier Letterer"
                url = "https://github.com/Darkona"
            }
        }
        scm {
            url = "https://github.com/Darkona/logged"
            connection = "scm:git:git://github.com/Darkona/logged.git"
            developerConnection = "scm:git:ssh://git@github.com/Darkona/logged.git"
        }
    }

}

publishing {
    publications.withType(MavenPublication).configureEach {
        versionMapping {
            usage('java-api')     { fromResolutionResult() }
            usage('java-runtime') { fromResolutionResult() }
        }
    }
}

dependencyManagement {
    imports {
        mavenBom SpringBootPlugin.BOM_COORDINATES
        mavenBom("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.18.1")
    }
}

dependencies {
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    api "org.springframework.boot:spring-boot-starter-aop"
    compileOnly("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter")

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation platform('org.junit:junit-bom:5.10.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory.set(
            layout.buildDirectory.dir("generated/sources/annotationProcessor/${name}")
    )
}

test {
    useJUnitPlatform()
}

compileJava.dependsOn(processResources)